### ISSUE TITLE
Correct support for multi dimensions

### ISSUE THREAD

**Issue by dfeyer** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#106]
We need to update the current implementation to update all node variants in the Indexer and not only the current like it's done now.

Check how it's done in the SimpleSearch adaptor:
https://github.com/Flowpack/Flowpack.SimpleSearch.ContentRepositoryAdaptor/blob/master/Classes/Flowpack/SimpleSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php

**Comment by daniellienert** [comment]
@dfeyer: This one should be fixed with https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/108 ?

**Comment by dfeyer** [comment]
Yes solve with #108
