### ISSUE TITLE
Regression: indexing fails if no "language" dimension is present

### ISSUE THREAD

**Issue by robertlemke** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#112]
https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/108 introduced a regression by hardcoding the "language" dimension into the NodeIndexer. There are, however, sites which don't have a "language" dimension or which might have dimensions with other names fulfilling the same role like a language.

We need to revert that behaviour or at least make it compatible with other dimension setups.
@dfeyer

**Comment by dfeyer** [comment]
Too bad :(

We can avoid the use of the FlowQuery and use a Context, like this, to get node in other dimension:

```
$context = $this->contextFactory->create(array('workspaceName' => $workspaceName, 'dimensions' => $combination));
$node = $context->getNodeByIdentifier($nodeIdentifier);
```

If we don't use the FlowQuery we don't need to targetDimension and the this bug can be solved.

**Comment by dfeyer** [comment]
For site without dimensions the indexing is just skipped ... shame on me ... will push a PR tomorrow
