### ISSUE TITLE
Add support for async indexer

### ISSUE THREAD

**Issue by dfeyer** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#121]
Currently the ES index is build during the request, this can be a problem for bigger setup, or complex index configuration. We also need per ex. in Neos to create a full index when we create a new user or workspace, this can take some times so we need to be able to do that async

**Comment by dfeyer** [comment]
Currently we use an external package to do bulk indexing based on job queue, need to refactor a bit to support the new jobqueue packages: https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer

The next step will be to make it possible to do live indexing in async way. I think that we can introduce a Interface to make this possible with external package.

**Comment by dfeyer** [comment]
Now our package support Asynchronous live indexing:
https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/releases/tag/2.0.3

**Comment by daniellienert** [comment]
Meanwhile the package is part of Flowpack and maintained alongside this package
