### ISSUE TITLE
ElasticSearchQueryBuilder::getTotalItems() always return NULL

### ISSUE THREAD

**Issue by bwaidelich** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#139]
`ElasticSearchQueryBuilder::getTotalItems()` checks for a key `total` in the result but that never exist. Instead the total hits are returned in `$this->results['hits']['total']` instead.

So shouldn't:
```php
    public function getTotalItems()
    {
        if (array_key_exists('total', $this->result)) {
            return (int)$this->result['total'];
        }
    }
```

be changed to sth like:

```php
    public function getTotalItems()
    {
        if (isset($this->result['hits']['total'])) {
            return (int)$this->result['hits']['total'];
        }
        return 0;
    }
```
?

**Comment by bwaidelich** [comment]
If someone ( @skurfuerst @dfeyer ?) can confirm this, I'll happily prepare a PR

**Comment by dfeyer** [comment]
It's really weird ... I will check you fix when I'm back from holiday, if I forgot, ping me on slack.

**Comment by dfeyer** [comment]
@bwaidelich Can you rebase your PR and I think we can merge it

**Comment by bwaidelich** [comment]
@dfeyer done, see #140 thx for checking
