### ISSUE TITLE
Stabilize `nodeindex:build` command

### ISSUE THREAD

**Issue by bwaidelich** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#141]
The current `nodeindex:build` implementation is not capable of indexing an existing site with a lot of nodes because it consumes too much memory for any system to handle.
There is a `--limit` flag but it doesn't split the tasks in junks but instead just stops after x nodes. What's the usecase for this?
Besides it would be useful to be able to only index certain dimension combinations and/or node types.

But most importantly it should be possible to be able to process single nodes/batches in separate processes (so this might be related to #121).

For a current project I hooked it our [JobQueue packages](https://packagist.org/packages/flowpack/jobqueue-common) to intercept the `NodeIndexingManage::indexNode()` call and create a job that is handled in (multiple) separate workers.
This most probably won't be faster because each worker has to boot up the framework, fetch the node again and index it.. But it is more stable and scalable and it should be possible to process a batch of nodes at once per worker to find the sweet spot between memory consumption and performance..

**Comment by dfeyer** [comment]
We build this package to handle job based on job queue:
https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer

**Comment by dfeyer** [comment]
And I think this change can improve the memory usage:

**Comment by dfeyer** [comment]
#142 Can help to update a single node, pretty useful when working on the indexing configuration

**Comment by daniellienert** [comment]
In the meantime, the nodeindex:build command is split up in several subtasks to handle several steps of indexing and also indexing of different dimensions / workspaces separately. 
Thats why I would consider that issue as closed. 
Please open it again if there are still problems.
