### ISSUE TITLE
Hide page in search?

### ISSUE THREAD

**Issue by Torsten85** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#147]
Hey there, 
just tested this plugin and it works great, thanks!
One thing that come to mind is that I've some sites that should not appear in the search results (e.g. the page that is shown after successful contact form submit, or the search page itself).

I've added a property to `TYPO3.Neos:Document`called `hideInSearch`. But how do I adjust the query to only consider pages that do not have this attribute?

Something like
`Search.query(site).dontMatch('hideInSearch', true).fulltext(this.searchTerm)``

Thanks in advance
Torsten

**Comment by dfeyer** [comment]
So for the late answer, check the documentation https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#doing-arbitrary-queries

I think ```queryFilter("filterType", {hideInSearch: false})``` should work for you
