### ISSUE TITLE
The [filtered] query is deprecated, please use a [bool] query instead with a [must] clause for the query part and a [filter] clause for the filter part.

### ISSUE THREAD

**Issue by dfeyer** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#178]
Look like we use a deprecated query, and we expose some internals, like in QueryBuilder::appendAtPath we need to plan how to move to more decoupled query

**Comment by daniellienert** [comment]
@dfeyer - that should be fixed in the meantime. We use that query style in the ES 5 driver already.

**Comment by daniellienert** [comment]
Ok, I declare that as fixed now. Please feel free to reopen the ticket if needed.
