### ISSUE TITLE
illegal_argument_exception: mapper [heading] cannot be changed from type [int] to [string]

### ISSUE THREAD

**Issue by sbruggmann** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#181]
**Situation**

Two different Packages with different NodeTypes which both are using a Property named "heading", but one is type of int and one is type of string.

**Action**

`./flow nodeindex:build`

**Result**

```
Array
(
    [root_cause] => Array
        (
            [0] => Array
                (
                    [type] => illegal_argument_exception
                    [reason] => mapper [heading] cannot be changed from type [int] to [string]
                )

        )

    [type] => illegal_argument_exception
    [reason] => mapper [heading] cannot be changed from type [int] to [string]
)
```

**Comment by aertmann** [comment]
Can confirm

**Comment by aertmann** [comment]
This answer is a bit depressing http://stackoverflow.com/questions/34513132/elasticsearch-what-to-do-if-fields-have-the-same-name-but-multiple-mapping

**Comment by kdambekalns** [comment]
Basically: no way to fix this, and it is going to be stricter with later versions of Elasticsearch.
