### ISSUE TITLE
`nodeindex:build` creates internal workspaces if they don't exist yet

### ISSUE THREAD

**Issue by jobee** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#213]
A new internal workspace will be created, if the workspace flag is set to a none existing workspace `nodeindex:build --workspace=this-workspace-does-not-exist`

<img width="920" alt="es-index-workspace" src="https://cloud.githubusercontent.com/assets/5636715/26685342/1b01827e-46ea-11e7-9a92-9415b5087526.png">

(Neos 2.3 / ContentRepositoryAdaptor 3.0.x-dev)

**Comment by kdambekalns** [comment]
Fixed with #215
