### ISSUE TITLE
Querying count() when no results returns always 2

### ISSUE THREAD

**Issue by peterbucher** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#225]
Using Neos 3.0, Elasticsearch 2.3 and the most current versions of this ContentRepositoryAdaptor.
When using Flowpack.SearchPlugin and an extended PaginateController, i ran into an Issue.

On a query which is an instance of "Neos\ContentRepository\Search\Search\QueryBuilderInterface" i call the count() method like this, to get the count of all search results:

```
$this->resultCount = $this->query->count();
```

Unfortunately this gives strange Results:

- If there are one result found with a search query, the count() method returns 1, which is correct.
- If there are multiple results found with a search query, the count() method returns e.g. 4, which is correct.
- Now,
 if there are no results found with a search query, **the count() method returns 2, which is incorrect**.

I analyzed the problem and found a fix, but it is more a hack than a fix.

When doing a search to Elasticsearch, the query will be the same, as the query which is submitted, when i call the count() method.

The count() method is implemented as a request to "/_count" (https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/blob/master/Classes/Eel/ElasticSearchQueryBuilder.php#L596) and extracts then the count (https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/blob/master/Classes/Eel/ElasticSearchQueryBuilder.php#L600)

_I tried to change this request to "/_search" and extract the count from this. And voila, the count is always correct._

I guess the problem lies in the query which the ContentRepositoryAdaptor generates.

See PR #226 

Example Query which was used:
```
{
  "query": {
    "filtered": {
      "query": {
        "bool": {
          "must": [
            {
              "match_all": []
            },
            {
              "query_string": {
                "query": "\"fsdfsdfsd\""
              }
            }
          ]
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "bool": {
                "should": [
                  {
                    "term": {
                      "__parentPath": "/sites/cms"
                    }
                  },
                  {
                    "term": {
                      "__path": "/sites/cms"
                    }
                  }
                ]
              }
            },
            {
              "terms": {
                "__workspace": [
                  "live"
                ]
              }
            },
            {
              "term": {
                "__dimensionCombinationHash": "9dfdd8b029869edee199f9f9f920b723"
              }
            },
            {
              "term": {
                "__typeAndSupertypes": "Neos.Neos:Document"
              }
            }
          ],
          "should": [],
          "must_not": [
            {
              "term": {
                "_hidden": true
              }
            },
            {
              "range": {
                "_hiddenBeforeDateTime": {
                  "gt": "now"
                }
              }
            },
            {
              "range": {
                "_hiddenAfterDateTime": {
                  "lt": "now"
                }
              }
            },
            {
              "term": {
                "hiddenInSearchResults": true
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by kdambekalns** [comment]
I tried to reproduce this error (using Elasticsearch 2.3.1) without success. In all cases the number of documents returned was the same.

That being said, while reading https://github.com/elastic/elasticsearch/issues/13928 it seems the `_count` API is merely syntactic sugar and the equivalent to using `_search?size=0`. Given that, a difference is even more unlikely…

On top of that, that bug has never been observed by anyone else.

@peterbucher Could you please double check if that error is still reproducible for you?

**Comment by peterbucher** [comment]
@kdambekalns i am with the version 4.0.5 of the ContentRepositoryAdaptor and cannot longer reproduce this issue.

**Comment by kdambekalns** [comment]
Thanks for checking! I'll close this one, then…
