### ISSUE TITLE
Did we need to remove the support for Types and move to one index per concrete NodeType

### ISSUE THREAD

**Issue by dfeyer** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#230]
This issue is to keep track of informations regarding our usage of Types, wrong based on the official documentation: https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html#_type_takeaways

But we need to take care of this https://stackoverflow.com/questions/14465668/elastic-search-multiple-indexes-vs-one-index-and-types-for-different-data-sets (sharding issue with a lots of indices)

**Comment by dfeyer** [comment]
And for those who don't follow Elasticsearch closly, this is the situation that we will face for ES6
https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch

**Comment by daniellienert** [comment]
Closing this in favor of #306
