### ISSUE TITLE
Bug: Highlighting doesn't add em-tags 

### ISSUE THREAD

**Issue by akappler** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#232]
Hi,
I had some trouble with getting the search word highlighted in the result.
The problem with the current version is, that elasticsearch doesn't think that the fields definition in the highlight section of the search query doesn't match with the searched fields. Therefore the highlighting doesn't work and changes via `.highlight()` eel helper have no effects. 

My suggested solution would be to add the missing parameters `fields => ['__fulltext*']` in the FilteredQuery.php at the `fulltext` function.

After I added this, the search word got highlighted as expected.

A quick workaround is to tweak the fusion searchQuery in your own package like this:

```
prototype(Flowpack.SearchPlugin:Search) < prototype(Neos.Neos:Content) {

    queryStringFields = Neos.Fusion:RawArray {
        fields = Neos.Fusion:RawArray {
            0 = "__fulltext*"
        }
    }

    searchQuery = ${this.searchTerm ? Search.query(site).fulltext(this.searchTerm).request('query.filtered.query.bool.must.1.query_string', this.queryStringFields).nodeType('Neos.Neos:Document') : null}    
}
```

I'll add an PR.

**Comment by akappler** [comment]
See https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/233

**Comment by mficzel** [comment]
I solved this problem in a custom EEL-Helper this way. I think this is not optimal but it looks like onyl the fields that are explicitly searched are available for highlighting in elastic 2+
```
/**
     * @param ElasticSearchQueryBuilder $request
     * @param string $searchWord
     * @return ElasticSearchQueryBuilder
     */
    public function fulltext(ElasticSearchQueryBuilder $request, $searchWord) {

        $request->setByPath('query.filtered.query.bool.should', [
            [
                'query_string' => [
                    'query' => json_encode($searchWord),
                    'fields' => ['__fulltext*']
                ]
            ],
            [
                'query_string' => [
                    'query' => json_encode($searchWord)
                ]
            ]
        ]);

        $request->setByPath('query.filtered.query.bool.minimum_should_match', 1);

        $request->highlight(150,3);

        return $request;
    }
```

**Comment by daniellienert** [comment]
Hey @akappler - this should now definitely be fixed with https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/263 - could you please have a look, you feedback is appreciated.

**Comment by daniellienert** [comment]
This should be fixed now in current master. So I dare to close this issue. If you need this bug to be fixed in an older version please have a look at https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/262 and give some feedback.
