### ISSUE TITLE
Support for Elasticsearch 6.0+

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#306]
Its about time to support Elasticsearch versions > 6.0 as the currently supported version 5.6 is EOL since 2019-3-11 (https://www.elastic.co/support/eol).

As you may know, the main issue is the removal of the Type feature (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/removal-of-types.html) which was used to separate the different node types.
There are two different approaches to solve this, using an explicit type field and one type per index.

The one-type-per-index option would make it possible to give an equal named property in two different node types different data types. Since ES 2.x thats not possible anymore. The disadvantage is, that this approach would end up in a lot of indexes / shards - especially when multiplied with separate indexes per language.

In big projects with a lot of NodeTypes and languages, this could easily reach ES recommended limits - see:

* https://www.elastic.co/de/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster
* https://stackoverflow.com/questions/14465668/elastic-search-multiple-indexes-vs-one-index-and-types-for-different-data-sets

The explicit-type-field approach would keep the number of shards small and would have no disadvantages in terms of data types to the current situation. It is also way easier to implement.

So I would prefer the explicit type field approach.

**Comment by johannessteu** [comment]
I think due to the architecture of neos there is no real option beside a custom type field at all.

**Comment by dfeyer** [comment]
> I think due to the architecture of neos there is no real option beside a custom type field at all.

I agree, we will explode the number of shard on big project, ... and those project really need Elastic, so better to not take any risk just for the shake of property name colisision.

**Comment by kitsunet** [comment]
> risk just for the shake of property name colisision
that problem exists today already so I guess we do not loose much.

**Comment by daniellienert** [comment]
Note to self: 
- https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html
