### ISSUE TITLE
Avoid underscorce prefix in field name

### ISSUE THREAD

**Issue by gerhard-boden** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#309]
Maybe we should try to avoid underscores in our field names when doing the mapping, since this raises issues when using Kibana. Also see https://github.com/elastic/kibana/issues/14856.

Not sure how much effort it would take to just avoid the `_` prefixes or if its even worth it for the probably small number of Kibana users.

**Comment by daniellienert** [comment]
Hey @gerhard-boden , I also stumbled upon this recently. As the next major versions of the ES packages are breaking anyways it could be good Idea to change this. We need some prefix nevertheless. What could taht be? 'neos_', 'Internal_'?
