### ISSUE TITLE
min and max aggregation not working when using querybuilder

### ISSUE THREAD

**Issue by bweinzierl** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#355]
While term aggregations work fine you cannot use a max or min aggregation. (Probably also not other aggregation types)

This query fails with elasticsearch error:
`query = ${Search.query(site).nodeType('My.Website:Document.MyPage').fieldBasedAggregation('myAggregation', 'myintproperty', 'min')}`

Problem is that fieldBasedAggregation() in `Classes/Eel/ElasticSearchQueryBuilder.php` always adds a size configuration to the aggregation but elasticsearch does not like a size for min or max aggregations. Probably also not for average and other stuff.

Here is a patch that fixes this for min and max:
```
Index: Classes/Eel/ElasticSearchQueryBuilder.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Classes/Eel/ElasticSearchQueryBuilder.php	(date 1602836143606)
+++ Classes/Eel/ElasticSearchQueryBuilder.php	(date 1602836143606)
@@ -420,6 +420,10 @@
             ]
         ];
 
+        if ($type === 'min' || $type === 'max') {
+            unset($aggregationDefinition[$type]['size']);
+        }
+
         $this->aggregation($name, $aggregationDefinition, $parentPath);
 
         return $this;
```

**Comment by bweinzierl** [comment]
I think best solution would be to just make the size parameter default to `null` and then only set the default if a term aggregation is used. This way the fix would not be 100% non breaking if there is another aggregation type that can use the size attribute. I dont know elasticsearch well enought though. Anybody knows which aggregation types have size attribute?

**Comment by daniellienert** [comment]
AFAIK the default for the size parameter is 10. So if we set the size parameter to null and only apply it if set as suggested I don't see much breakiness.
Would you take care of the PR @bweinzierl ?
