### ISSUE TITLE
Nodes are indexed dimensionCombination^2 times

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#359]
Currently we cycle through all dimensionCombinations once in:

https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/blob/master/Classes/Command/NodeIndexCommandController.php#L181

and then in: 

https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/blob/301154e92de26c8b0b70170fb8aea1f9540a8104/Classes/Indexer/NodeIndexer.php#L309

which leads to indexing `dimensionCombination^2 * nodes` where it only should be `dimensionCombination * nodes`.

While the outer loop is needed to traverse the tree for every dimension, the inner one should not be needed.

**Comment by daniellienert** [comment]
It seems that the inner loop is needed for indexing content to dimensions which have fallbacks defined: 

Thats the node structure in the tests:

![image](https://user-images.githubusercontent.com/642226/102583391-e99d3200-4104-11eb-8c1e-adbf538b9323.png)

The "doc_untrans" is not translated, but as de and dk fallback to en_us, the content should be also indexed to these languages. 

The inner loop needs to be adjusted to only loop over the dimensions that fallback to the dimension which is currently indexed.

**Comment by daniellienert** [comment]
Should finally be solved with https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/363

**Comment by kdambekalns** [comment]
Would the fixes be applicable to v7 of the adapter? That would make them available for te Neos 5.3 LTS version…
