### ISSUE TITLE
Multiple Datasets in Index

### ISSUE THREAD

**Issue by mgoldbeck** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#44]
For one Node there are several datasets in the Elastic Index. So there are to many Nodes indexed which has at least influences for the result number, when all results are shown,
For searching with a dedicated search term the result number is the correct one. (SEARCHING DIRECTLY IN THE INDEX))

This behavior probably depends on the first indexing of the data. For every workspace, all nodes are indexed. If there are no nodes in the user-jondoe workspace the nodes are indexed for workspace live.

**Comment by mgoldbeck** [comment]
As short update. Still the same behaviour and even worse with more than one dimension.

**Comment by dfeyer** [comment]
@mgoldbeck Can you check if your issue is solved by 3605673b5efa392aed8818efefa59f57ae8939e3 and 041b556fd80850f372848327be711f2d2513a0a2 (merged on master)

**Comment by dfeyer** [comment]
@mgoldbeck Can you update this one based on recent master ?

**Comment by mgoldbeck** [comment]
@dfeyer I have no access to this index any longer ;) But will try to replay it with other data.

**Comment by dfeyer** [comment]
@mgoldbeck Any news ?

**Comment by mgoldbeck** [comment]
Will close it because I can't reproduce it.
