### ISSUE TITLE
count() is not working

### ISSUE THREAD

**Issue by hphoeksma** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#50]
The _count call doesn't work.

It seems to trip over the 'fields' => array('__path') part.
I couldn't find a way to fix it, so I solved it in my own QueryBuilder doing:

	public function count() {
		$response = $this->elasticSearchClient->getIndex()->request('GET', '/_search', array(), json_encode($this->request));
		$treatedContent = $response->getTreatedContent();
		return (int)$treatedContent['hits']['total'];
	}

Not so nice. But better suggestions welcome ;-)

**Comment by dfeyer** [comment]
Can this issue be closed now ?

**Comment by hphoeksma** [comment]
It seems to be working well now, so I would say yes!
