### ISSUE TITLE
ElasticSearch timezone configuration (since version 1.4)

### ISSUE THREAD

**Issue by whythecode** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#70]
Since version 1.4 there's a configuration for setting the time_zone to be used in a query (See [the docs](https://github.com/elastic/elasticsearch/blob/master/docs/reference/query-dsl/filters/range-filter.asciidoc#date-options), [the commit](https://github.com/elastic/elasticsearch/commit/d28b8c6dae46c922d5f52f0a59d9e1d0b4d37ad7), and [the original issue](https://github.com/elastic/elasticsearch/issues/3729)). (Note that this is apparently still missing for aggregations.)

This is important for all queries which use relative dates and/or "magic" keywords ("now", etc).

One thing that's not clear to me, is how ElasticSearch figures out what "now" means. In either case, it's a lot safer if we make sure it's using the currently configured PHP Timezone, since that's what the node dates also use.

It would probably be ideal to add this option to the default ElasticSearchQueryBuilder query.

**Comment by yaramayer** [comment]
Hi @skurfuerst,

it seems ElasticSearch actually uses Timestamps when creating "now" etc, so as long as the dates are correctly indexed in the first place, everything should be fine. I think we can close this. Can you please verify (insanity check)?

Thanks a lot!
